openapi: 3.0.0
info:
  title: Book Service API
  version: "1.0"
paths:
  /books:
    get:
      summary: Get all books
      responses:
        "200":
          description: List of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
      responses:
        "201":
          description: Book added

  /books/{book_id}:
    get:
      summary: Get book by ID
      parameters:
        - in: path
          name: book_id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Book found
        "404":
          description: Book not found
